// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package harvester

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatBuilderConfiguration is an auto-generated flat version of BuilderConfiguration.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatBuilderConfiguration struct {
	Namespace                  *string `mapstructure:"namespace" required:"false" cty:"namespace" hcl:"namespace"`
	NamePrefix                 *string `mapstructure:"name_prefix" required:"false" cty:"name_prefix" hcl:"name_prefix"`
	CPU                        *int64  `mapstructure:"cpu" required:"false" cty:"cpu" hcl:"cpu"`
	Memory                     *string `mapstructure:"memory" required:"false" cty:"memory" hcl:"memory"`
	PreventBuilderImageCleanup *bool   `mapstructure:"prevent_builder_image_cleanup" required:"false" cty:"prevent_builder_image_cleanup" hcl:"prevent_builder_image_cleanup"`
}

// FlatMapstructure returns a new FlatBuilderConfiguration.
// FlatBuilderConfiguration is an auto-generated flat version of BuilderConfiguration.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*BuilderConfiguration) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatBuilderConfiguration)
}

// HCL2Spec returns the hcl spec of a BuilderConfiguration.
// This spec is used by HCL to read the fields of BuilderConfiguration.
// The decoded values from this spec will then be applied to a FlatBuilderConfiguration.
func (*FlatBuilderConfiguration) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"namespace":                     &hcldec.AttrSpec{Name: "namespace", Type: cty.String, Required: false},
		"name_prefix":                   &hcldec.AttrSpec{Name: "name_prefix", Type: cty.String, Required: false},
		"cpu":                           &hcldec.AttrSpec{Name: "cpu", Type: cty.Number, Required: false},
		"memory":                        &hcldec.AttrSpec{Name: "memory", Type: cty.String, Required: false},
		"prevent_builder_image_cleanup": &hcldec.AttrSpec{Name: "prevent_builder_image_cleanup", Type: cty.Bool, Required: false},
	}
	return s
}

// FlatBuilderSource is an auto-generated flat version of BuilderSource.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatBuilderSource struct {
	Name        *string `mapstructure:"name" cty:"name" hcl:"name"`
	OSType      *string `mapstructure:"os_type" cty:"os_type" hcl:"os_type"`
	ImageType   *string `mapstructure:"image_type" cty:"image_type" hcl:"image_type"`
	URL         *string `mapstructure:"url" required:"false" cty:"url" hcl:"url"`
	DisplayName *string `mapstructure:"display_name" required:"false" cty:"display_name" hcl:"display_name"`
	Checksum    *string `mapstructure:"checksum" required:"false" cty:"checksum" hcl:"checksum"`
	Cleanup     *bool   `mapstructure:"cleanup" required:"false" cty:"cleanup" hcl:"cleanup"`
}

// FlatMapstructure returns a new FlatBuilderSource.
// FlatBuilderSource is an auto-generated flat version of BuilderSource.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*BuilderSource) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatBuilderSource)
}

// HCL2Spec returns the hcl spec of a BuilderSource.
// This spec is used by HCL to read the fields of BuilderSource.
// The decoded values from this spec will then be applied to a FlatBuilderSource.
func (*FlatBuilderSource) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"name":         &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"os_type":      &hcldec.AttrSpec{Name: "os_type", Type: cty.String, Required: false},
		"image_type":   &hcldec.AttrSpec{Name: "image_type", Type: cty.String, Required: false},
		"url":          &hcldec.AttrSpec{Name: "url", Type: cty.String, Required: false},
		"display_name": &hcldec.AttrSpec{Name: "display_name", Type: cty.String, Required: false},
		"checksum":     &hcldec.AttrSpec{Name: "checksum", Type: cty.String, Required: false},
		"cleanup":      &hcldec.AttrSpec{Name: "cleanup", Type: cty.Bool, Required: false},
	}
	return s
}

// FlatBuilderTarget is an auto-generated flat version of BuilderTarget.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatBuilderTarget struct {
	Namespace        *string `mapstructure:"namespace" required:"false" cty:"namespace" hcl:"namespace"`
	DisplayName      *string `mapstructure:"display_name" required:"false" cty:"display_name" hcl:"display_name"`
	StorageClassName *string `mapstructure:"storage_class_name" required:"false" cty:"storage_class_name" hcl:"storage_class_name"`
}

// FlatMapstructure returns a new FlatBuilderTarget.
// FlatBuilderTarget is an auto-generated flat version of BuilderTarget.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*BuilderTarget) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatBuilderTarget)
}

// HCL2Spec returns the hcl spec of a BuilderTarget.
// This spec is used by HCL to read the fields of BuilderTarget.
// The decoded values from this spec will then be applied to a FlatBuilderTarget.
func (*FlatBuilderTarget) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"namespace":          &hcldec.AttrSpec{Name: "namespace", Type: cty.String, Required: false},
		"display_name":       &hcldec.AttrSpec{Name: "display_name", Type: cty.String, Required: false},
		"storage_class_name": &hcldec.AttrSpec{Name: "storage_class_name", Type: cty.String, Required: false},
	}
	return s
}

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName      *string                   `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType    *string                   `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion    *string                   `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug          *bool                     `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce          *bool                     `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError        *string                   `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars       map[string]string         `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars  []string                  `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	HarvesterURL         *string                   `mapstructure:"harvester_url" cty:"harvester_url" hcl:"harvester_url"`
	HarvesterToken       *string                   `mapstructure:"harvester_token" cty:"harvester_token" hcl:"harvester_token"`
	HarvesterNamespace   *string                   `mapstructure:"harvester_namespace" cty:"harvester_namespace" hcl:"harvester_namespace"`
	BuilderSource        *FlatBuilderSource        `mapstructure:"builder_source" cty:"builder_source" hcl:"builder_source"`
	BuilderConfiguration *FlatBuilderConfiguration `mapstructure:"builder_configuration" cty:"builder_configuration" hcl:"builder_configuration"`
	BuilderTarget        *FlatBuilderTarget        `mapstructure:"builder_target" cty:"builder_target" hcl:"builder_target"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"harvester_url":              &hcldec.AttrSpec{Name: "harvester_url", Type: cty.String, Required: false},
		"harvester_token":            &hcldec.AttrSpec{Name: "harvester_token", Type: cty.String, Required: false},
		"harvester_namespace":        &hcldec.AttrSpec{Name: "harvester_namespace", Type: cty.String, Required: false},
		"builder_source":             &hcldec.BlockSpec{TypeName: "builder_source", Nested: hcldec.ObjectSpec((*FlatBuilderSource)(nil).HCL2Spec())},
		"builder_configuration":      &hcldec.BlockSpec{TypeName: "builder_configuration", Nested: hcldec.ObjectSpec((*FlatBuilderConfiguration)(nil).HCL2Spec())},
		"builder_target":             &hcldec.BlockSpec{TypeName: "builder_target", Nested: hcldec.ObjectSpec((*FlatBuilderTarget)(nil).HCL2Spec())},
	}
	return s
}
